version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/.ssh/simple-board
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/.ssh/simple-board
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
