version: '3'
services:
  spring_app1:
    container_name: Spring-Tomcat-1
    image: haechansomg/simple-board:was01
    environment:
      - JAVA_OPTS=-javaagent:/home/ubuntu/scouter/agent.java/scouter-agent-java-2.20.0.jar -Dscouter.config=/home/ubuntu/scouter/agent.java/conf/was01.conf -Dobj_name=WAS-01
    ports:
      - 8080:8080
  spring_app2:
    container_name: Spring-Tomcat-2
    image: haechansomg/simple-board2:was02
    environment:
      - JAVA_OPTS=-javaagent:/home/ubuntu/scouter/agent.java/scouter-agent-java-2.20.0.jar -Dscouter.config=/home/ubuntu/scouter/agent.java/conf/was02.conf -Dobj_name=WAS-02
    ports:
      - 8081:8081
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    expose:
      - "6379"