version: '3'
services:
  #  grafana:
  #    image: grafana/grafana
  #    ports:
  #      - 3000:3000
  #  prometheus:
  #    image: prom/prometheus
  #    ports:
  #      - 9090:9090
  #    volumes:
  #      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  spring_app1:
    container_name: Spring-Tomcat-1
    image: haechansomg/simple-board:was01
    ports:
      - 8080:8080
  #  spring_app2:
  #    container_name: Spring-Tomcat-2
  #    image: haechansomg/simple-board2:was02
  #    ports:
  #      - 8081:8081
  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    #  redis-exporter:
    #    image: oliver006/redis_exporter
    #    ports:
    #      - 9121:9121
    #    environment:
    #      REDIS_ADDR: "redis:6379"
    links:
      - redis
#      - prometheus