version: '3'
services:
  spring_app1:
    container_name: Spring-Tomcat-1
    image: haechansomg/simple-board
    ports:
      - 8080:8080
  spring_app2:
    container_name: Spring-Tomcat-2
    image: haechansomg/simple-board
    ports:
      - 8081:8081
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    expose:
      - "6379"