FROM openjdk:17-jdk

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-javaagent:/home/ubuntu/scouter/agent.java/scouter-agent-java-2.20.0.jar","-Duser.timezone=Asia/Seoul","-jar","app.jar"]
