FROM openjdk:17-jdk

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
COPY scouter/agent.java/scouter-agent-java-2.20.0.jar scouter-agent-java-2.20.0.jar
ENTRYPOINT ["java","-javaagent:scouter-agent-java-2.20.0.jar","-Duser.timezone=Asia/Seoul","-jar","app.jar"]
