FROM openjdk:17-jdk

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-javaagent:/home/ubuntu/scouter/agent.java/scouter.agent.jar","-Dscouter.config=/home/ubuntu/scouter/agent.java/conf/was01.conf","-Dobj_name=WAS-01","-Duser.timezone=Asia/Seoul","-jar","app.jar"]
